decision:
  en: "Talk to the conference participants and solve theirquests."
prompt:
  en: "You are at a conference about applied mathematics. You enter the scene after a conference slot, the audience leaves the room and discusses the presentations they have just heard. Some may have problems you can help them with."
  # - inc.mayor
  # - inc.citizenPunk
  # - inc.lawyer
scenery:
  mardiDesk:
    spawn: { x: 363, y: 553 }
  coffeeTable:
    spawn: { x: 1327, y: 551 }
  libraryDesk:
    spawn: { x: 1902, y: 547 }
npcs:
  MathPerson1:
    name:
      en: "I need a name"
    type: citizenBlue
    spawn: { x: 819, y: 448 }
    dialogue:
    - type: sequence
      items:
        - text:
            en: "This is my default dialogue."
  robot:
    name:
      en: "Robot (my default dialogue is chosen randomly)"
    spawn: { x: 1079, y: 500 }
    dialogue:
      - type: random
        items:
          - text:
              en: "“Mathematics is the queen and servant of sciences”, according to a quote by Carl F. Gauss."
          - text:
              en: "Is Mathematics even a science?"
          - text:
              en: "Research data are not only empirical records."
          - text:
              en: "In modern mathematical research, we can find many types of data."
          - text:
              en: "One key difference between mathematics and other sciences is the existence of proofs."
          - text:
              en: "Have you subscribed to the MaRDI newsletter, yet?"
          - text:
              en: "Mathematics is not especially well placed in terms of managing research data and software in comparison to other fields."
          - text:
              en: "Data must be accompanied by rich metadata that describes it."
          - text:
              en: "Storing and archiving research data is not a trivial matter and should be planned carefully."
          - text:
              en: "Information is data tagged with meaning."
          - text:
              en: "Reusing knowledge is ingrained in the practice of scientific research as the basis of verifiability."
          - text:
              en: "Access to research information is the most fundamental principle for spreading science across the scientific community and society."
          - text:
              en: "I :love: math!"
          - text:
              en: "Your math is data!"
  Tabea:
    name:
      en: "Tabea"
    spawn: { x: 420, y: 538 }
    type: citizenBraid
    actAs: 
      - '_mardiHelpdesk'
    dialogue:
      - text:
          en: "I work at the MaRDI help desk. I will help you with questions about data."
  MathPerson2:
    name:
      en: "I need a name."
    spawn: { x: 1212, y: 333 }
    type: citizenLila
    dialogue:
      - text:
          en: "This is my default dialogue."
  Librarian:
    name:
      en: "I need a name."
    spawn: { x: 1929, y: 530 }
    type: citizenHoodie
    dialogue:
      - text:
          en: "I am a librarian."
  Barista:
    name:
      en: "I need a name."
    spawn: { x: 1400, y: 500 }
    type: barista
    dialogue:
      - type: sequence
        items:
          - text:
              en: "I brought some cookies. But you wanna know a secret?"
          - text:
              en: "The cake is a lie."
  Christiane:
    name:
      en: "Christiane"
    type: mayor
    spawn: { x: 350, y: 538 }
    actAs: 
      - '_mardiHelpdesk'
    dialogue:
      - text:
          en: "Do you know, there is a real MaRDI help desk at the MaRDI website? Check it out after the game."
  Dog:
    name:
      en: "Momo"
    spawn: { x: 1650, y: 580 }
    type: dogTan
    dialogue:
      - text:
          en: "Woof!"
  MathPerson3:
    name:
      en: "I need a name"
    type: journalist
    spawn: { x: 471, y: 333 }
    dialogue:
      - text:
          en: "This is my default dialogue."
  coffeeMachine:
    type: invisible
    name:
      en: "PercoLaTeX 3000™"
    spawn: { x: 1229, y: 560 }
    dialogue:
      - type: first
        items:
          - text:
              en: "Let's integrate some coffee into your day!"
            responses:
              - text:
                  en: "Espresso"
                then: brew
              - text:
                  en: "Latte"
                then: brew
              - text:
                  en: "Cappuccino"
                then: brew
      - id: brew
        type: sequence
        items:
          - text:
              en: "Beep! Whirrrrrr..."
          - text:
              en: "Ssshhhhhhhh... drip, drip, drip."
  webBrowser:
    type: invisible
    name:
      en: "MaRDI Portal"
    spawn: { x: 1547, y: 322 }
    dialogue:
      - text:
          en: "Where do you want to go?"
        responses:
          - text:
              en: "MathModDB"
            thenText: "MathModDB is a database of mathematical models. It helps organize and link mathematical models, offering structured insights into mathematical modelling and related computational tasks. "
          - text:
              en: "MathAlgoDB"
            thenText: "MathAlgoDB Knowledge Graph for Scientific Computing connects mathematical algorithms, models, problems, and software in a structured knowledge graph."
          - text:
              en: "MaRDMO"
            thenText: "MaRDMO is an extension of the Research Data Management Organiser (RDMO) designed to facilitate the documentation, integration, and sharing of mathematical models, interdisciplinary workflows, and algorithms."
          - text:
              en: "GMCI"
            thenText: "GMCI stands for the community Graphical Modelling and Causal Inference. On this platform, we curate and present topical datasets, dataset collections, and metadata."
quests:  
  hairycat:
    npc: Dog
    mood: exclamation
    available:
      dialogue:
        - type: sequence
          items:
            - text:
                en: "Hi there. I share my home with several cats. Their furr is so different from mine and behaves weirdly."
            - text:
                en: "But you know what's cool? I did some experiments and figured out, when and why the furr is wavy, frizzy, soft, fluffy etc. I even created a mathematical model and published it (on zenodo?)!"
            - text:
                en: "Now, I would like to connect my model to other research problems, maybe even from different academic disciplines, so everyone can make use of it. Would you help me?"
              responses:
                - text:
                    en: "Sure, I'll help you."
                  thenText:
                    en: "Great! I am not sure, where I should share it. Can you find out what is a good place to share a mathematical model?"
                  set: [ 'quest.hairycat.active' ]
                - text:
                    en: "No, sorry. I must be halucinating - am I talking to a dog?"
                  thenText:
                    en: "I am not an illusion! Come back anytime to help or chat."
    stages:
      - cond: 'found.hairycat.mathmoddb'
        target: Dog
        prompt:
          en: "Tell the dog Momo about MathModDB."
        dialogues:
          Dog:
            - type: sequence
              items:
              - text:
                 en: "Great. Now I know MathModDB is the best place for my Hairy Cat Model!"
              - text:
                  en: "Wold you help me with choosing the right information on the research context, the mathematical structure of the model, and how the model is used computationally?"
                responses:
                  - text:
                      en: "Ok, I'll help you with the mathematical structure."
                    then: MS  
                  - text:
                      en: "Ok, I'll help you with the research context."
                    then: RC  
                  - text:
                      en: "Ok, I'll help you with the computational use."
                    then: CU  
                  - text:
                      en: "No, you are such a clever dog, you can do that yourself."
                    thenText: "Alright, I will figure it out myself. Thank you for your help!"
                    set: [ 'quest.hairycat.done', 'pnt.love.hairycat' , 'op.quest.hairycat' ]
              - id: CU     
                type: sequence
                items:
                  - text:
                      en: "Thank you! So, what would be the computational use for my Hairy Cat Model?"
                    responses:
                      - text:
                          en: Link to specific computational tasks associated with your mathematical model.
                        thenText: Ah, good idea. I will do that. Thank you!
                        set: [ 'quest.hairycat.done', 'pnt.love.hairycat' , 'op.quest.hairycat' ] 
                      - text:
                          en: "One computational task would be 'Continuum hair estimation'."
                        thenText: "Ah, good idea. I'll keep that in mind. Thank you!"
                        set: [ 'quest.hairycat.done', 'pnt.love.hairycat' , 'op.quest.hairycat' ]
                      - text:
                          en: "Remember to include the cat collar boundary condition."
                        thenText: "Ah, good idea. I will do that. Thank you!"
                        set: [ 'quest.hairycat.done', 'pnt.love.hairycat' , 'op.quest.hairycat' ]
              - id: RC     
                type: sequence
                items:
                  - text:
                      en: "Thank you! So, which research context should I choose?"
                    responses:
                      - text:
                          en: Link your model to a research problem and an academic discipline.
                        thenText: Ah, good idea. I will do that. Thank you!
                        set: [ 'quest.hairycat.done', 'pnt.love.hairycat' , 'op.quest.hairycat' ] 
                      - text:
                          en: "Link it to the problem 'Understanding the physical properties of cat fur'."
                        thenText: "Ah, good idea. I'll do that. Thank you!"
                        set: [ 'quest.hairycat.done', 'pnt.love.hairycat' , 'op.quest.hairycat' ]
                      - text:
                          en: "The academic discipline could be 'Applied Felinology'."
                        thenText: "Ah, good idea. I'll keep that in mind. Thank you!"
                        set: [ 'quest.hairycat.done', 'pnt.love.hairycat' , 'op.quest.hairycat' ]
              - id: MS     
                type: sequence
                items:
                  - text:
                      en: "Thank you! So, which mathematical structure does my model use?"
                    responses:
                      - text:
                          en: Link your model to the mathematical expressions and the quantities.
                        thenText: Ah, good idea. I will do that. Thank you!
                        set: [ 'quest.hairycat.done', 'pnt.love.hairycat' , 'op.quest.hairycat' ] 
                      - text:
                          en: "One of the quantities is the electric charge as well as the fluffiness."
                        thenText: "Ah, good idea. I'll keep that in mind. Thank you!"
                        set: [ 'quest.hairycat.done', 'pnt.love.hairycat' , 'op.quest.hairycat' ]
                      - text:
                          en: "One equation is probably: fluffiness(T,cat) = -a*T + cat."
                        thenText: "Of course, I know! Thank you anyway!"
                        set: [ 'quest.hairycat.done', 'pnt.love.hairycat' , 'op.quest.hairycat' ]

      - cond: '^found.hairycat.mathmoddb'
        prompt:
          en: "Find out where best to share a mathematical model."
        dialogues:
          webBrowser:
            - text:
                en: "Mathematical models are best shared in the knowledge graph for mathematical models. Please use MaRDI's service MathModDB."
              responses:
                - text:
                    en: "Thank you. That's the information I was looking for."
                  then: Details
                - text:
                    en: "Thank you. But what is a Knowledge Graph?"
                  then: KG
            - id: KG
              type: sequence
              items:
                - text:
                    en: "(add an explanation for Knowledge graphs, suitable for the audience)."
                  then: Details
            - id: Details
              type: sequence
              items:
                - text:
                    en: "When you enter the model, you should also give information on the research context, the mathematical structure of the model, and how the model is used computationally."
                  set: [ 'found.hairycat.mathmoddb' ]
          Librarian:
            - type: sequence
              items:
              - text:
                  en: "I am not sure. I can do a quick search for publications for you."
              - text:
                  en: ":clock: 3 minutes later…"
              - text:
                  en: "There are quite a few publications by MaRDI. They have a help desk here at the conference. It is probably best to go over and talk to them."
          _mardiHelpdesk:
            - type: sequence
              items:
                - text:
                    en: "Mathematical models are best shared in the knowledge graph for mathematical models. Please use MaRDI's service MathModDB."
                - text:
                    en: "By the way, a knowledge graph is ... (add an explanation for Knowledge graphs, suitable for the audience)."
                - text:
                    en: "When you enter the model, you should also give information on the research context, the mathematical structure of the model, and how the model is used computationally."
                  set: [ 'found.hairycat.mathmoddb' ]
          MathPerson1:
            - text:
                en: "Oh, there is a MaRDI service for that. You could check the MaRDI Portal on the web, which one to use."
          Dog:
            - text:
                en: "Please, you promised to help me. Ask around, where I can publish my mathematical model."
          MathPerson2:
            - text:
                en: "Please, don't disturb me. I am coding..."

ending:
  dialogue:
    - type: sequence
      items:
        - cond: 'quest.hairycat.done'
          class: 'citizensEmpowered'
          type: sequence
          items:
            - text:
                en: 'You helped Momo to add the Hairy Cat model to MathModDB.'
        - cond: '^quest.hairycat.done'
          type: sequence
          items:
            - text:
                en: "You did not help Momo to publish the Hairy Cat Model. Try again."
