game:
  devModeShortcuts: false
  languages: ['en']
  duration: 600
  cameraPresets:
    walking:
      offset:
        x: 0
        y: -1.35
      zoom: 1
    talking:
      offset:
        x: 0
        y: -0.8
      zoom: 0.5
    drone:
      offset:
        x: 0
        y: 0
      zoom: 0.5
town:
  width: 2048
  height: 768
textures:
  bundles:
    - name: 'town-view'
      assets:
        - name: 'town-bg'
          srcs: 'conference.png'
        - name: 'town-collmap'
          srcs: 'conference-collmap.png'
        - name: 'player-1'
          srcs: 'player-1.json'
        - name: 'player-2'
          srcs: 'player-2.json'
        - name: 'player-3'
          srcs: 'player-3.json'
        - name: 'npcs-demo'
          srcs: 'npcs-demo.json'
        - name: 'mood-balloon'
          srcs: 'mood-balloon.json'
        - name: 'map-markers'
          srcs: 'map-markers.json'
        - name: 'icons'
          srcs: 'icons.json'
        - name: 'target-arrow'
          srcs: 'target-arrow.png'
        - name: 'guide-arrow'
          srcs: 'guide-arrow.png'
        - name: 'mardiDesk'
          srcs: 'mardi-desk-1.png'
        - name: 'coffeeTable'
          srcs: 'coffee-table.png'
        - name: 'libraryDesk'
          srcs: 'library-desk.png'
players:
  1:
    color: '#27a6a8'
    spawn: { x: 100, y: 700 }
    gamepadMapping:
      axes:
        horizontal: 0
        vertical: 1
        invertHorizontal: true
        invertVertical: true
storylines:
  - coffeecats
i18n:
  ui:
    title:
      en: 'CC & CC'
    pressStart:
      en: "Press Ⓐ or space to start"
    decisionMade:
      en: 'Thank you for playing! Here are your quest achievements:'
    waitingToBegin:
      en: 'Get ready! A new game will begin soon.'
    waitingToEnd:
      en: 'Waiting for the other players…'
    pressToContinue:
      en: 'Press Ⓐ or space to continue'
    defaultPrompt:
      en: 'Talk to the characters with a :speech_bubble: and solve their quests, or get a coffee.'
    includedInDecision:
      en: 'Included in the decision'
    inclusionBarTitle:
      en: 'Who decides?'


